# See https://pre-commit.com/#new-hooks
# Requires composer to be installed locally
- id: composer-validate
  name: composer validate
  description: Validates composer.json and composer.lock
  entry: composer validate
  language: system
  pass_filenames: false
  files: '^composer.(json|lock)$'

- id: composer-validate-strict
  name: composer validate (strict mode)
  description: Validates composer.json and composer.lock with --strict mode enabled
  entry: composer validate --strict
  language: system
  pass_filenames: false
  files: '^composer.(json|lock)$'
