# See https://pre-commit.com/#new-hooks
- id: composer-validate
  name: composer validate
  description: Validates composer.json and composer.lock
  entry: bin/composer validate
  language: script
  pass_filenames: false
  files: '^composer.(json|lock)$'
