name: "Autoloader"

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

permissions:
  contents: read

jobs:
  tests:
    name: "Autoloader"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install locked dependencies"
        run: "cd tests/Composer/Test/Autoload/MinimumVersionSupport; composer config platform --unset && composer install"

      - name: "Install oldest supported PHP version for autoloader"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1"
          php-version: "5.6"

      - name: "Check the autoloader can be executed"
        run: "cd tests/Composer/Test/Autoload/MinimumVersionSupport; php main.php"
